build:
  image: python:3.10-bullseye
  script:
    - python3 -m pip install -U pip
    - pip3 config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
    - pip3 install -r requirements.txt
    - mkdocs build
