site_name: 实验物理的大数据方法 FAQ
site_description: 'FAQ for Big Data in Experimental Physics'
site_author: 'Teaching Team of Big Data in Experimental Physics'
copyright: 'Copyright &copy; 2020 Teaching Team of Big Data in Experimental Physics, Tsinghua University. All Rights Reserved.'

theme: 
  name: 'material'
  language: 'zh'
  icon:
    logo: material/help
    repo: fontawesome/brands/github
  features:
    - tabs
    - instant

repo_name: 'physics-data/faq'
repo_url: 'https://github.com/physics-data/faq'

extra:
  pagetime: 'on'

nav:
  - 主页: index.md
  - 先修要求: prerequisite.md
  - 环境配置:
    - Windows 环境配置: env/windows.md
    - Linux 环境配置: env/linux.md
    - macOS 环境配置: env/mac.md
  - 工具:
    - SSH 服务端配置: tool/sshd.md
    - Git 使用与配置: tool/git.md
    - 编辑器使用与配置: tool/editor.md
    - 常用命令行工具: tool/command.md
  - 教程:
    - Linux 下的路径: tutorials/path.md
    - GitLab CI 配置: tutorials/ci.md
    - GitHub Workflow 配置: tutorials/workflow.md
    - 常用的软件包的安装方式: tutorials/install.md
    - 并行计算与加速手段: tutorials/parallel-accel.md
    - 白盒标准: tutorials/whitebox.md
  - 常见问题:
    - APT 相关问题: misc/apt.md
    - Git 相关问题: misc/git.md
    - WSL 相关问题: misc/wsl.md
    - 命令行相关问题: misc/command.md
    - vitables 相关问题: misc/vitables.md
    - macOS 相关问题: misc/mac.md
    - mail 作业依赖打环问题: misc/mail.md
    - 课程相关问题: misc/course.md

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
  - git-authors:
      show_contribution: true
      show_line_count: true

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - footnotes
  - def_list
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list

